version: '3'
services:
  search_engine:
    image: solr
    container_name: search_engine
    ports:
      - '8984:8983'
    volumes:
      - type: bind
        source: ./solr
        target: /var/solr/data/

volumes:
  data:
